// Configuration for Control Panel
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    
    channelName : "pupster",
    displayName : "Pupster"
, };


function getChannelName() { return panelSettings.channelName; }

function getDisplayName() { return panelSettings.displayName; }
