// Configuration for Control Panel
// Automatically Generated by PhantomBot at Startup
// Do NOT Modify! Overwritten when PhantomBot is restarted!
var panelSettings = {
    panelPort   : 25004,
    channelName : "pupster",
    auth        : "lPVPfYqTPVnv0PvurYJ0n0gClN0xVv",
    http        : "http://"
,     displayName : "Pupster"
, };

function getPanelPort() { return panelSettings.panelPort; }
function getChannelName() { return panelSettings.channelName; }
function getAuth() { return panelSettings.auth; }
function getProtocol() { return panelSettings.http; }
function getDisplayName() { return panelSettings.displayName; }
